"""add proposal explanations and agent threads

Revision ID: 26c1e2c38a2c
Revises: 6a49c94f1707
Create Date: 2026-10-06 09:41:27.759508
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# Revision identifiers, used by Alembic.
revision: str = "26c1e2c38a2c"
down_revision: str | None = "6a49c94f1707"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("proposals", sa.Column("explanation", sa.Text(), nullable=True))
    op.add_column("proposals", sa.Column("explained_by", sa.String(), nullable=True))
    op.add_column("proposals", sa.Column("draft_message", sa.Text(), nullable=True))
    op.add_column("proposals", sa.Column("agent_thread_id", sa.String(length=64), nullable=True))
    op.create_unique_constraint(
        op.f("uq_proposals_agent_thread_id"), "proposals", ["agent_thread_id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("uq_proposals_agent_thread_id"), "proposals", type_="unique")
    op.drop_column("proposals", "agent_thread_id")
    op.drop_column("proposals", "draft_message")
    op.drop_column("proposals", "explained_by")
    op.drop_column("proposals", "explanation")
    # ### end Alembic commands ###
