"""add customers, sales, bills, proposals and orders

Revision ID: cdcfb845e0f3
Revises: a0a17f52457d
Create Date: 2026-10-01 10:30:23.270490
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# Revision identifiers, used by Alembic.
revision: str = "cdcfb845e0f3"
down_revision: str | None = "a0a17f52457d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "customers",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("code", sa.String(length=10), nullable=False),
        sa.Column("shop_name", sa.String(), nullable=False),
        sa.Column("contact_person", sa.String(), nullable=True),
        sa.Column("phone", sa.String(), nullable=True),
        sa.Column("area", sa.String(), nullable=True),
        sa.Column("credit_limit", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("credit_days", sa.Integer(), nullable=False),
        sa.Column("on_hold", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("hold_reason", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("credit_days >= 0", name=op.f("ck_customers_credit_days_not_negative")),
        sa.CheckConstraint(
            "credit_limit >= 0", name=op.f("ck_customers_credit_limit_not_negative")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_customers")),
        sa.UniqueConstraint("code", name=op.f("uq_customers_code")),
    )
    op.create_table(
        "customer_bills",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("upload_id", sa.Integer(), nullable=False),
        sa.Column("customer_id", sa.Integer(), nullable=False),
        sa.Column("bill_no", sa.String(length=20), nullable=False),
        sa.Column("bill_date", sa.Date(), nullable=False),
        sa.Column("amount", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column(
            "received", sa.Numeric(precision=10, scale=2), server_default="0", nullable=False
        ),
        sa.Column("balance", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("source_row", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "amount >= 0 AND received >= 0", name=op.f("ck_customer_bills_amounts_not_negative")
        ),
        sa.ForeignKeyConstraint(
            ["customer_id"], ["customers.id"], name=op.f("fk_customer_bills_customer_id_customers")
        ),
        sa.ForeignKeyConstraint(
            ["upload_id"],
            ["uploads.id"],
            name=op.f("fk_customer_bills_upload_id_uploads"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_customer_bills")),
        sa.UniqueConstraint(
            "upload_id", "bill_no", name=op.f("uq_customer_bills_upload_id_bill_no")
        ),
    )
    op.create_index(
        op.f("ix_customer_bills_customer_id"), "customer_bills", ["customer_id"], unique=False
    )
    op.create_table(
        "proposals",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("kind", sa.String(), nullable=False),
        sa.Column("status", sa.String(), server_default="pending", nullable=False),
        sa.Column("product_id", sa.Integer(), nullable=True),
        sa.Column("customer_id", sa.Integer(), nullable=True),
        sa.Column("numbers", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("basis", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("reason", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("decided_by", sa.String(), nullable=True),
        sa.Column("decision_note", sa.String(), nullable=True),
        sa.CheckConstraint(
            "kind IN ('reorder', 'payment_reminder', 'hold_orders')",
            name=op.f("ck_proposals_kind_valid"),
        ),
        sa.CheckConstraint(
            "status IN ('pending', 'approved', 'rejected', 'superseded')",
            name=op.f("ck_proposals_status_valid"),
        ),
        sa.CheckConstraint(
            "(product_id IS NULL) <> (customer_id IS NULL)",
            name=op.f("ck_proposals_exactly_one_subject"),
        ),
        sa.ForeignKeyConstraint(
            ["customer_id"], ["customers.id"], name=op.f("fk_proposals_customer_id_customers")
        ),
        sa.ForeignKeyConstraint(
            ["product_id"], ["products.id"], name=op.f("fk_proposals_product_id_products")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_proposals")),
    )
    op.create_index(op.f("ix_proposals_customer_id"), "proposals", ["customer_id"], unique=False)
    op.create_index(op.f("ix_proposals_product_id"), "proposals", ["product_id"], unique=False)
    op.create_index(
        "uq_proposals_pending_customer",
        "proposals",
        ["kind", "customer_id"],
        unique=True,
        postgresql_where=sa.text("status = 'pending' AND customer_id IS NOT NULL"),
    )
    op.create_index(
        "uq_proposals_pending_product",
        "proposals",
        ["kind", "product_id"],
        unique=True,
        postgresql_where=sa.text("status = 'pending' AND product_id IS NOT NULL"),
    )
    op.create_table(
        "sales_lines",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("upload_id", sa.Integer(), nullable=False),
        sa.Column("sale_date", sa.Date(), nullable=False),
        sa.Column("customer_id", sa.Integer(), nullable=False),
        sa.Column("product_id", sa.Integer(), nullable=False),
        sa.Column("qty", sa.Integer(), nullable=False),
        sa.Column("unit_price", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("amount", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.CheckConstraint("qty > 0", name=op.f("ck_sales_lines_qty_positive")),
        sa.ForeignKeyConstraint(
            ["customer_id"], ["customers.id"], name=op.f("fk_sales_lines_customer_id_customers")
        ),
        sa.ForeignKeyConstraint(
            ["product_id"], ["products.id"], name=op.f("fk_sales_lines_product_id_products")
        ),
        sa.ForeignKeyConstraint(
            ["upload_id"],
            ["uploads.id"],
            name=op.f("fk_sales_lines_upload_id_uploads"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sales_lines")),
    )
    op.create_index(
        op.f("ix_sales_lines_customer_id"), "sales_lines", ["customer_id"], unique=False
    )
    op.create_index(op.f("ix_sales_lines_product_id"), "sales_lines", ["product_id"], unique=False)
    op.create_index(op.f("ix_sales_lines_upload_id"), "sales_lines", ["upload_id"], unique=False)
    op.create_table(
        "payment_reminders",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("customer_id", sa.Integer(), nullable=False),
        sa.Column("proposal_id", sa.Integer(), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("status", sa.String(), server_default="ready", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('ready', 'sent', 'cancelled')",
            name=op.f("ck_payment_reminders_status_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["customer_id"],
            ["customers.id"],
            name=op.f("fk_payment_reminders_customer_id_customers"),
        ),
        sa.ForeignKeyConstraint(
            ["proposal_id"],
            ["proposals.id"],
            name=op.f("fk_payment_reminders_proposal_id_proposals"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_payment_reminders")),
        sa.UniqueConstraint("proposal_id", name=op.f("uq_payment_reminders_proposal_id")),
    )
    op.create_index(
        op.f("ix_payment_reminders_customer_id"), "payment_reminders", ["customer_id"], unique=False
    )
    op.create_table(
        "purchase_orders",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("supplier_id", sa.Integer(), nullable=False),
        sa.Column("proposal_id", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(), server_default="approved", nullable=False),
        sa.Column("created_by", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('approved', 'sent', 'received', 'cancelled')",
            name=op.f("ck_purchase_orders_status_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["proposal_id"], ["proposals.id"], name=op.f("fk_purchase_orders_proposal_id_proposals")
        ),
        sa.ForeignKeyConstraint(
            ["supplier_id"], ["suppliers.id"], name=op.f("fk_purchase_orders_supplier_id_suppliers")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_purchase_orders")),
        sa.UniqueConstraint("proposal_id", name=op.f("uq_purchase_orders_proposal_id")),
    )
    op.create_index(
        op.f("ix_purchase_orders_supplier_id"), "purchase_orders", ["supplier_id"], unique=False
    )
    op.create_table(
        "purchase_order_lines",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("purchase_order_id", sa.Integer(), nullable=False),
        sa.Column("product_id", sa.Integer(), nullable=False),
        sa.Column("qty", sa.Integer(), nullable=False),
        sa.Column("unit_cost", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.CheckConstraint("qty > 0", name=op.f("ck_purchase_order_lines_qty_positive")),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
            name=op.f("fk_purchase_order_lines_product_id_products"),
        ),
        sa.ForeignKeyConstraint(
            ["purchase_order_id"],
            ["purchase_orders.id"],
            name=op.f("fk_purchase_order_lines_purchase_order_id_purchase_orders"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_purchase_order_lines")),
    )
    op.create_index(
        op.f("ix_purchase_order_lines_product_id"),
        "purchase_order_lines",
        ["product_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_purchase_order_lines_purchase_order_id"),
        "purchase_order_lines",
        ["purchase_order_id"],
        unique=False,
    )
    op.add_column("issues", sa.Column("customer_id", sa.Integer(), nullable=True))
    op.create_index(op.f("ix_issues_customer_id"), "issues", ["customer_id"], unique=False)
    op.create_foreign_key(
        op.f("fk_issues_customer_id_customers"), "issues", "customers", ["customer_id"], ["id"]
    )
    # ### end Alembic commands ###
    # Added by hand: autogenerate doesn't detect new CHECK constraints on existing tables.
    op.create_check_constraint(
        op.f("ck_uploads_kind_valid"),
        "uploads",
        "kind IN ('stock_register', 'customers', 'outstanding_dues', 'sales_history')",
    )


def downgrade() -> None:
    op.drop_constraint(op.f("ck_uploads_kind_valid"), "uploads", type_="check")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("fk_issues_customer_id_customers"), "issues", type_="foreignkey")
    op.drop_index(op.f("ix_issues_customer_id"), table_name="issues")
    op.drop_column("issues", "customer_id")
    op.drop_index(
        op.f("ix_purchase_order_lines_purchase_order_id"), table_name="purchase_order_lines"
    )
    op.drop_index(op.f("ix_purchase_order_lines_product_id"), table_name="purchase_order_lines")
    op.drop_table("purchase_order_lines")
    op.drop_index(op.f("ix_purchase_orders_supplier_id"), table_name="purchase_orders")
    op.drop_table("purchase_orders")
    op.drop_index(op.f("ix_payment_reminders_customer_id"), table_name="payment_reminders")
    op.drop_table("payment_reminders")
    op.drop_index(op.f("ix_sales_lines_upload_id"), table_name="sales_lines")
    op.drop_index(op.f("ix_sales_lines_product_id"), table_name="sales_lines")
    op.drop_index(op.f("ix_sales_lines_customer_id"), table_name="sales_lines")
    op.drop_table("sales_lines")
    op.drop_index(
        "uq_proposals_pending_product",
        table_name="proposals",
        postgresql_where=sa.text("status = 'pending' AND product_id IS NOT NULL"),
    )
    op.drop_index(
        "uq_proposals_pending_customer",
        table_name="proposals",
        postgresql_where=sa.text("status = 'pending' AND customer_id IS NOT NULL"),
    )
    op.drop_index(op.f("ix_proposals_product_id"), table_name="proposals")
    op.drop_index(op.f("ix_proposals_customer_id"), table_name="proposals")
    op.drop_table("proposals")
    op.drop_index(op.f("ix_customer_bills_customer_id"), table_name="customer_bills")
    op.drop_table("customer_bills")
    op.drop_table("customers")
    # ### end Alembic commands ###
