"""add whatsapp orders and enquiries

Revision ID: 6a49c94f1707
Revises: cdcfb845e0f3
Create Date: 2026-10-06 09:18:47.264597
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# Revision identifiers, used by Alembic.
revision: str = "6a49c94f1707"
down_revision: str | None = "cdcfb845e0f3"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "customer_orders",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("upload_id", sa.Integer(), nullable=False),
        sa.Column("customer_id", sa.Integer(), nullable=True),
        sa.Column("sender", sa.String(), nullable=False),
        sa.Column("first_sent_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("source_lines", sa.ARRAY(sa.Integer()), nullable=False),
        sa.Column("unclear", sa.ARRAY(sa.Text()), server_default="{}", nullable=False),
        sa.Column("status", sa.String(), server_default="awaiting_confirmation", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('awaiting_confirmation', 'confirmed', 'rejected')",
            name=op.f("ck_customer_orders_status_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["customer_id"], ["customers.id"], name=op.f("fk_customer_orders_customer_id_customers")
        ),
        sa.ForeignKeyConstraint(
            ["upload_id"],
            ["uploads.id"],
            name=op.f("fk_customer_orders_upload_id_uploads"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_customer_orders")),
    )
    op.create_index(
        op.f("ix_customer_orders_customer_id"), "customer_orders", ["customer_id"], unique=False
    )
    op.create_index(
        op.f("ix_customer_orders_upload_id"), "customer_orders", ["upload_id"], unique=False
    )
    op.create_table(
        "enquiries",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("upload_id", sa.Integer(), nullable=False),
        sa.Column("customer_id", sa.Integer(), nullable=True),
        sa.Column("sender", sa.String(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("source_line", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["customer_id"], ["customers.id"], name=op.f("fk_enquiries_customer_id_customers")
        ),
        sa.ForeignKeyConstraint(
            ["upload_id"],
            ["uploads.id"],
            name=op.f("fk_enquiries_upload_id_uploads"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_enquiries")),
    )
    op.create_index(op.f("ix_enquiries_customer_id"), "enquiries", ["customer_id"], unique=False)
    op.create_index(op.f("ix_enquiries_upload_id"), "enquiries", ["upload_id"], unique=False)
    op.create_table(
        "customer_order_lines",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("order_id", sa.Integer(), nullable=False),
        sa.Column("product_id", sa.Integer(), nullable=True),
        sa.Column("written", sa.String(), nullable=False),
        sa.Column("qty", sa.Integer(), nullable=False),
        sa.Column("unit_written", sa.String(), nullable=True),
        sa.Column("matched_on", sa.String(), nullable=True),
        sa.CheckConstraint("qty > 0", name=op.f("ck_customer_order_lines_qty_positive")),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["customer_orders.id"],
            name=op.f("fk_customer_order_lines_order_id_customer_orders"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
            name=op.f("fk_customer_order_lines_product_id_products"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_customer_order_lines")),
    )
    op.create_index(
        op.f("ix_customer_order_lines_order_id"), "customer_order_lines", ["order_id"], unique=False
    )
    op.create_index(
        op.f("ix_customer_order_lines_product_id"),
        "customer_order_lines",
        ["product_id"],
        unique=False,
    )
    op.add_column("proposals", sa.Column("order_id", sa.Integer(), nullable=True))
    op.create_index(op.f("ix_proposals_order_id"), "proposals", ["order_id"], unique=False)
    op.create_index(
        "uq_proposals_pending_order",
        "proposals",
        ["order_id"],
        unique=True,
        postgresql_where=sa.text("status = 'pending' AND order_id IS NOT NULL"),
    )
    op.create_foreign_key(
        op.f("fk_proposals_order_id_customer_orders"),
        "proposals",
        "customer_orders",
        ["order_id"],
        ["id"],
    )
    op.add_column("uploads", sa.Column("content_sha256", sa.String(length=64), nullable=True))
    op.create_index(op.f("ix_uploads_content_sha256"), "uploads", ["content_sha256"], unique=False)
    # ### end Alembic commands ###
    # Added by hand: autogenerate doesn't detect changed CHECK constraints.
    _replace_check(
        "uploads",
        "status_valid",
        "status IN ('processing', 'processed', 'failed')",
    )
    _replace_check(
        "uploads",
        "kind_valid",
        "kind IN ('stock_register', 'customers', 'outstanding_dues', 'sales_history', "
        "'whatsapp_chat')",
    )
    _replace_check(
        "proposals",
        "kind_valid",
        "kind IN ('reorder', 'payment_reminder', 'hold_orders', 'confirm_order')",
    )
    _replace_check(
        "proposals", "exactly_one_subject", "num_nonnulls(product_id, customer_id, order_id) = 1"
    )


def downgrade() -> None:
    # Remove what the older constraints don't allow, then restore them.
    op.execute("DELETE FROM proposals WHERE kind = 'confirm_order'")
    op.execute("DELETE FROM uploads WHERE kind = 'whatsapp_chat'")
    op.execute("UPDATE uploads SET status = 'failed' WHERE status = 'processing'")
    _replace_check(
        "proposals", "exactly_one_subject", "(product_id IS NULL) <> (customer_id IS NULL)"
    )
    _replace_check(
        "proposals", "kind_valid", "kind IN ('reorder', 'payment_reminder', 'hold_orders')"
    )
    _replace_check(
        "uploads",
        "kind_valid",
        "kind IN ('stock_register', 'customers', 'outstanding_dues', 'sales_history')",
    )
    _replace_check("uploads", "status_valid", "status IN ('processed', 'failed')")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_uploads_content_sha256"), table_name="uploads")
    op.drop_column("uploads", "content_sha256")
    op.drop_constraint(
        op.f("fk_proposals_order_id_customer_orders"), "proposals", type_="foreignkey"
    )
    op.drop_index(
        "uq_proposals_pending_order",
        table_name="proposals",
        postgresql_where=sa.text("status = 'pending' AND order_id IS NOT NULL"),
    )
    op.drop_index(op.f("ix_proposals_order_id"), table_name="proposals")
    op.drop_column("proposals", "order_id")
    op.drop_index(op.f("ix_customer_order_lines_product_id"), table_name="customer_order_lines")
    op.drop_index(op.f("ix_customer_order_lines_order_id"), table_name="customer_order_lines")
    op.drop_table("customer_order_lines")
    op.drop_index(op.f("ix_enquiries_upload_id"), table_name="enquiries")
    op.drop_index(op.f("ix_enquiries_customer_id"), table_name="enquiries")
    op.drop_table("enquiries")
    op.drop_index(op.f("ix_customer_orders_upload_id"), table_name="customer_orders")
    op.drop_index(op.f("ix_customer_orders_customer_id"), table_name="customer_orders")
    op.drop_table("customer_orders")
    # ### end Alembic commands ###


def _replace_check(table: str, name: str, condition: str) -> None:
    constraint = op.f(f"ck_{table}_{name}")
    op.drop_constraint(constraint, table, type_="check")
    op.create_check_constraint(constraint, table, condition)
